/**
 * Restore original article images by re-scraping source pages.
 *
 * This script targets articles whose current images are known fallbacks
 * (Pexels/Pixabay/placeholder) or truncated Unsplash URLs generated by
 * previous placeholder logic. It re-scrapes the original article page
 * using the same advanced image pipeline as the curator and updates
 * the database with the recovered image plus refreshed alt text.
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import { getBestArticleImage } from '../lib/services/image-scraper';
import { scrapeArticleImageAdvanced } from '../lib/services/advanced-image-scraper';
import { validateImageEnhanced } from '../lib/services/image-validator';
import { enhancedImageDescription } from '../lib/services/enhanced-image-description';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceRoleKey) {
  throw new Error('Supabase environment variables are missing.');
}

const supabase = createClient(supabaseUrl, serviceRoleKey);

function needsRestoration(imageUrl: string | null): boolean {
  if (!imageUrl) return true;

  const lower = imageUrl.toLowerCase();
  if (lower.includes('pexels.com') || lower.includes('pixabay.com')) return true;
  if (lower.includes('placeholder-ai-news')) return true;

  // Detect truncated Unsplash URLs like photo-1600004817?w=...
  const truncatedUnsplash = /^https:\/\/images\.unsplash\.com\/photo-\d+\?/;
  if (truncatedUnsplash.test(imageUrl)) return true;

  // Detect old fake Unsplash IDs without random suffix
  const unsplashNoSuffix = /^https:\/\/images\.unsplash\.com\/photo-\d+$/;
  if (unsplashNoSuffix.test(imageUrl)) return true;

  return false;
}

async function restoreImage(article: {
  id: string;
  title_en: string | null;
  title_es: string | null;
  source_url: string;
  image_url: string | null;
}): Promise<boolean> {
  const title = article.title_en || article.title_es || 'Untitled Article';
  console.log(`\n📰 Restoring image for: ${title.slice(0, 60)} (ID: ${article.id})`);

  let imageUrl: string | null = null;

  try {
    imageUrl = await getBestArticleImage(article.source_url);

    if (!imageUrl) {
      console.log('  [Restore] Fast scraper failed, trying advanced scraper...');
      const advanced = await scrapeArticleImageAdvanced(article.source_url);
      if (advanced && advanced.confidence > 0.4) {
        imageUrl = advanced.url;
        console.log(`  [Restore] ✅ Advanced scraper succeeded (method: ${advanced.method})`);
      }
    }
  } catch (error) {
    console.error('  [Restore] Scraping failed:', error instanceof Error ? error.message : error);
    return false;
  }

  if (!imageUrl) {
    console.warn('  [Restore] ❌ No image found, skipping update.');
    return false;
  }

  try {
    const validation = await validateImageEnhanced(imageUrl, {
      skipCache: true,
      skipComputerVision: false
    });

    if (!validation.isValid) {
      console.warn(`  [Restore] ❌ Image failed validation: ${validation.reason}`);
      return false;
    }

    let altTextEn: string | undefined;
    let altTextEs: string | undefined;

    if (enhancedImageDescription.isAvailable()) {
      try {
        const description = await enhancedImageDescription.generateDescription(imageUrl);
        altTextEn = description.accessibilityAlt;
        altTextEs = description.accessibilityAlt;
        console.log('  [Restore] ♿ Generated enhanced accessibility text');
      } catch (descriptionError) {
        console.warn('  [Restore] Alt text generation failed:', descriptionError instanceof Error ? descriptionError.message : descriptionError);
      }
    }

    const { error: updateError } = await supabase
      .from('news_articles')
      .update({
        image_url: imageUrl,
        image_alt_text_en: altTextEn || article.title_en || article.title_es,
        image_alt_text_es: altTextEs || article.title_es || article.title_en,
        updated_at: new Date().toISOString()
      })
      .eq('id', article.id);

    if (updateError) {
      console.error('  [Restore] ❌ Update failed:', updateError.message);
      return false;
    }

    console.log('  [Restore] ✅ Image restored successfully');
    return true;
  } catch (error) {
    console.error('  [Restore] Unexpected error:', error instanceof Error ? error.message : error);
    return false;
  }
}

async function main() {
  console.log('🔍 Scanning for articles needing image restoration...');

  const { data: articles, error } = await supabase
    .from('news_articles')
    .select('id, title_en, title_es, source_url, image_url')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('❌ Failed to fetch articles:', error.message);
    process.exit(1);
  }

  const targets = (articles || []).filter((article) => needsRestoration(article.image_url));
  console.log(`📊 Found ${targets.length} articles requiring restoration`);

  let restored = 0;
  let skipped = 0;

  for (const article of targets) {
    const success = await restoreImage(article);
    if (success) {
      restored++;
    } else {
      skipped++;
    }

    // Be nice to upstream servers
    await new Promise((resolve) => setTimeout(resolve, 500));
  }

  console.log('\n✅ Restoration complete');
  console.log(`  - Restored images: ${restored}`);
  console.log(`  - Failed / skipped: ${skipped}`);
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
